"""created_by_and_updated_by_columns_added

Revision ID: 11486e6fe4db
Revises: 0508455666ca
Create Date: 2024-12-17 16:46:12.274312

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11486e6fe4db"
down_revision: Union[str, None] = "0508455666ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authors", sa.Column("created_by", sa.String(), nullable=True))
    op.add_column("authors", sa.Column("updated_by", sa.String(), nullable=True))
    op.add_column("book_instances", sa.Column("created_by", sa.String(), nullable=True))
    op.add_column("book_instances", sa.Column("updated_by", sa.String(), nullable=True))
    op.add_column("books", sa.Column("created_by", sa.String(), nullable=True))
    op.add_column("books", sa.Column("updated_by", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("created_by", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("closed_by", sa.String(), nullable=True))
    op.add_column("readers", sa.Column("created_by", sa.String(), nullable=True))
    op.add_column("readers", sa.Column("updated_by", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("readers", "updated_by")
    op.drop_column("readers", "created_by")
    op.drop_column("orders", "closed_by")
    op.drop_column("orders", "created_by")
    op.drop_column("books", "updated_by")
    op.drop_column("books", "created_by")
    op.drop_column("book_instances", "updated_by")
    op.drop_column("book_instances", "created_by")
    op.drop_column("authors", "updated_by")
    op.drop_column("authors", "created_by")
    # ### end Alembic commands ###
